version: "3"

services:
  elasticsearch:
    image: ponsea/elasticsearch-ja-ko-zh:7.9.0
    build:
      context: ./
      args:
        - ES_IMG_VERSION=7.9.0
    ports:
      - "80:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
      xpack.security.enabled: "true"
      ELASTIC_PASSWORD: "<YOUR PASSWORD>"
      ES_JAVA_OPTS: "-Xms500m -Xmx500m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data:/usr/share/elasticsearch/data

volumes:
  data:
